inherit_from: .rubocop_todo.yml

# rubocopの動作全体に関わる設定
AllCops:
  Exclude:
    - 'bin/**/*' # 自動的に生成されるので除外する
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb' # 自動的に生成されるので除外する
    - 'public/**/*'
    - 'tmp/**/*'
    - '.tmp/**/*'
    - 'vendor/**/*'
    - 'Gemfile'

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false