language: ruby
rvm: 2.7.1
dist: trusty
services: postgresql
cache: bundler
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get update
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install postgresql-9.4
  - sudo chmod 777 /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" >  /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/9.4/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql --version
  - gem install bundler -v 2.0.2
before_script:
  - bundler -v
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: uk+fNHzTUVPRHXmFNaFQEobvCj79MM5oUJodmRXpvZ2PpjWws17y6gTis3eOT09tAQhrOWhANyEHRup+hLOA8g2y3ffE0qGyp7jr0/kE2Ro9ycd41VG5nl0HIaa/SmmF7YuJ+m+Anl7D4V87OoTKHBtEy2aXhn3UImHSrF7BSQWu++q4YoJWXQo2OGRxQwgFuY9Fb/dTOQeRMw3tQhQkD4B/98xe/h02xWSCt8nzaN+VivfBYjUl14AzP745b9/bIsxbAAO/7tmHGvl9NLRx5KlC6C49fZCOmyBSB/6NEmmBlmn0vdL7RnjXpOWRRwMeiDtN4xyTfeVsEe7GxAHrsn6HFJaYgzZxHy4CSvJg1Gug8K1QyCAf32XwCwQ6+cW1i9uriVwW0n/mZKP4aDJoxNjFfUhy0rfHYLLa2N4D8tYhQGrA2UoyvYbVwFsZ5ttR0JIxDkyyQulRzMJsYJeI/DdA6SYMTrIpS9NDMrl+2HGabHr3fXI6hV9ZnzPFUOeMGhieL7tcd3FnzKyBcmGC9y8jWzqBwB+eVWe0T9C3wEkE9zIGz+ObBQe7dUPjH1uhZ+3KIcJ1LOmJ6bnc7QTXpn3XKAN4JiElvbrVwxGynpP8onywOX9vbH24Xmv1OLWhJyCxAHw+vU2JlA1aPmu+2SiCQydPZf5Eakpk5UUk+MI=
  app: kanban-back
  on:
    repo: keita-hino/kanban_backend
