language: ruby
rvm: 2.7.1
dist: trusty
services: postgresql
cache: bundler
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get update
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install postgresql-9.4
  - sudo chmod 777 /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" >  /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/9.4/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/9.4/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql --version
  - gem install bundler -v 2.0.2
before_script:
  - bundler -v
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate

deploy:
  provider: heroku
  api_key:
    secure: HFR4nMe9CeC2HbpZfTdNYEy2Cg6rXkn+Vc58FpIwXFUtKNN5nudBDM4arvhw8qJ3+pj2Fwc7zQGiZ9TmoxYaQD7HRTe4S11FU6PSf4B6GLGFUmf4gUiMjQacHltBrQHPlMOhqk1LSoYQmyXGUdDpz+iRPh5GkBcS/FyBELTOghXHUVvoN+Wzbcu78/GqSLwh84bKJylcKvwuf2kp/NttLmbyvSlk4rRNysjXSQ6X0UBqbTQ8gWcwSgSoHVAdmHY3AiR9zRqj8Lm7nqZwN4h10WcrVFiwg4cMkW58APwegWz+DACM2hdNBYJhuBmgxAzJVyOSLUel+PGOBp+vXm/C+5ChpALPRu5kaNWhky0oaq0hOvMa6cwFwVtE36F1iArVQ1ZerHoiYNXu76452BANGdd/Gf+ROMbMT02QnUcTp/EY23caoL5lRbukDbJE5IEZZhEtG+4BBMiyOclkyegkQYyAMB9ntmpKgDHhiSWbFfwYfBlL2Lw7fi/8ITRqIyLHzPFX8ZEPuCGjHucwyllwz2CrFx+FqC5VZJi36Are912f4D1Hw9EhGw7AllLgxoQBa/m8hBfN9AwefhWWIX9PolmSV5v5u6p0YWw2J6EmZRlmHL7Xzy3xBnUA6mbn5a7oRITds7rWP82JuTOreZsjT4OvVB9uvZkAGs9xboPmR6Y=
  app: kanban-back
  on:
    repo: keita-hino/kanban_backend
